export const formats={AMERICANO:'Americano',TEAM_AMERICANO:'Team Americano',MIXED_AMERICANO:'Americano mixte',MEXICANO:'Mexicano',TEAM_MEXICANO:'Team Mexicano',MIXICANO:'Mixicano'};
export const rules={TIMED:'Au temps',FIXED_TOTAL:'Total de points',FIRST_TO:'Premier à X',WIN_BY_TWO:'Premier à X, écart de 2'};
export const fixed=f=>f.startsWith('TEAM_');
export const mixed=f=>f==='MIXED_AMERICANO'||f==='MIXICANO';
export const dynamic=f=>f.includes('MEXICANO')||f==='MIXICANO';
export function validateLibrary(data){
 if(!data||!Array.isArray(data.games))throw Error('Sauvegarde invalide.');
 const gameIds=new Set();
 for(const g of data.games){
  if(!g||typeof g.id!=='string'||!/^[a-zA-Z0-9-]{1,80}$/.test(g.id)||gameIds.has(g.id)||!Number.isFinite(g.created)||typeof g.closed!=='boolean'||typeof g.title!=='string'||g.title.length>80)throw Error('Identité de partie invalide.');gameIds.add(g.id);
  if(!Array.isArray(g.rounds)||!Array.isArray(g.revisions)||g.revisions.length>10000||!Array.isArray(g.withdrawn))throw Error('Structure invalide.');
  for(const [i,r] of g.rounds.entries()){if(!r||r.number!==i+1||!Array.isArray(r.matches)||!Array.isArray(r.byes))throw Error('Manche invalide.');for(const [j,m] of r.matches.entries())if(!m||m.id!==`${i+1}:${j+1}`)throw Error('Identifiant de match invalide.');}
  for(const r of g.revisions)if(!r||typeof r.match!=='string'||!/^\d+:\d+$/.test(r.match)||![r.before,r.after].every(a=>Array.isArray(a)&&a.length===2&&a.every(n=>Number.isInteger(n)&&n>=0&&n<=9999)))throw Error('Correction invalide.');
  if(!Array.isArray(g.players)||g.withdrawn.some(id=>!g.players.some(p=>p.id===id)))throw Error('Retrait invalide.');
  if(g.players.some(p=>!p||typeof p.id!=='string'||!/^p\d+$/.test(p.id)))throw Error('Identifiant joueur invalide.');
 }
 return validateContent(data);
}
export function validFinal(a,b,rule,target){if(![a,b].every(n=>Number.isInteger(n)&&n>=0&&n<=9999))return false;return rule==='TIMED'||rule==='FIXED_TOTAL'&&a+b===target||rule==='FIRST_TO'&&Math.max(a,b)===target&&Math.min(a,b)<target||rule==='WIN_BY_TWO'&&((Math.max(a,b)===target&&Math.min(a,b)<=target-2)||(Math.max(a,b)>target&&Math.abs(a-b)===2));}
export function ranking(g){const rows=g.players.map(p=>({...p,points:0,against:0,wins:0,played:0,h2h:0}));const by=Object.fromEntries(rows.map(p=>[p.id,p]));const done=g.rounds.flatMap(r=>r.matches).filter(m=>m.status==='done');for(const m of done)for(let t=0;t<2;t++)for(const id of m.teams[t]){const p=by[id];p.points+=m.score[t];p.against+=m.score[1-t];p.played++;p.wins+=+(m.score[t]>m.score[1-t]);}for(const p of rows)for(const m of done){const t=m.teams.findIndex(team=>team.includes(p.id));if(t<0)continue;for(const id of m.teams[1-t])if(by[id].points===p.points&&by[id].wins===p.wins)p.h2h+=m.score[t]-m.score[1-t];}return rows.sort((a,b)=>b.points-a.points||b.wins-a.wins||b.h2h-a.h2h||(b.points/(b.played||1)-a.points/(a.played||1))||(b.points-b.against)-(a.points-a.against)||a.name.localeCompare(b.name,'fr'));}
function shuffle(a,seed){a=[...a];for(let i=a.length-1;i>0;i--){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const j=seed%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
export function makeRound(g){const number=g.rounds.length+1,active=g.players.filter(p=>!g.withdrawn.includes(p.id));const rests=Object.fromEntries(active.map(p=>[p.id,g.rounds.filter(r=>r.byes.includes(p.id)).length]));let order=shuffle(active,g.seed+number);if(dynamic(g.format)&&number>1)order=ranking(g).filter(p=>!g.withdrawn.includes(p.id));const priority=new Map(order.map((p,i)=>[p.id,i]));const choose=ps=>[...ps].sort((a,b)=>rests[b.id]-rests[a.id]||priority.get(a.id)-priority.get(b.id));let teams=[];
if(fixed(g.format)){let pairs=g.players.filter((_,i)=>i%2===0).map((p,i)=>[p.id,g.players[2*i+1].id]).filter(t=>t.every(id=>!g.withdrawn.includes(id)));if(!dynamic(g.format)){if(pairs.length%2)pairs.push(null);for(let i=0;i<(number-1)%(pairs.length-1);i++)pairs.splice(1,0,pairs.pop());for(let i=0;i<pairs.length/2;i++)if(pairs[i]&&pairs[pairs.length-1-i])teams.push(pairs[i],pairs[pairs.length-1-i]);}else{pairs.sort((a,b)=>rests[b[0]]-rests[a[0]]||Math.min(...a.map(id=>priority.get(id)))-Math.min(...b.map(id=>priority.get(id))));teams=pairs.slice(0,pairs.length-pairs.length%2);}}
else{let selected;if(mixed(g.format)){const a=choose(order.filter(p=>p.group==='A')),b=choose(order.filter(p=>p.group==='B'));const n=Math.floor(Math.min(a.length,b.length)/2)*2;selected=[...a.slice(0,n),...b.slice(0,n)];}else selected=choose(order).slice(0,Math.floor(order.length/4)*4);selected.sort((a,b)=>priority.get(a.id)-priority.get(b.id));
const count=(x,y,opponent=false)=>g.rounds.reduce((n,r)=>n+r.matches.filter(m=>opponent?(m.teams[0].includes(x)&&m.teams[1].includes(y)||m.teams[1].includes(x)&&m.teams[0].includes(y)):m.teams.some(t=>t.includes(x)&&t.includes(y))).length,0);
if(dynamic(g.format)&&number>1){if(mixed(g.format)){const a=selected.filter(p=>p.group==='A'),b=selected.filter(p=>p.group==='B');for(let i=0;i<a.length;i+=2)teams.push([a[i].id,b[i+1].id],[a[i+1].id,b[i].id]);}else for(let i=0;i<selected.length;i+=4)teams.push([selected[i].id,selected[i+3].id],[selected[i+1].id,selected[i+2].id]);}
else{while(selected.length){const p=selected.shift();const candidates=selected.filter(q=>!mixed(g.format)||q.group!==p.group).sort((a,b)=>count(p.id,a.id)-count(p.id,b.id));const q=candidates[0];selected.splice(selected.indexOf(q),1);teams.push([p.id,q.id]);}const arranged=[];while(teams.length){const a=teams.shift();teams.sort((b,c)=>a.reduce((s,x)=>s+b.reduce((v,y)=>v+count(x,y,true),0),0)-a.reduce((s,x)=>s+c.reduce((v,y)=>v+count(x,y,true),0),0));arranged.push(a,teams.shift());}teams=arranged;}}
const matches=[];for(let i=0;i<teams.length;i+=2)matches.push({id:`${number}:${i/2+1}`,teams:[teams[i],teams[i+1]],score:[0,0],status:'scheduled'});if(!matches.length)throw Error('Il faut au moins quatre joueurs disponibles, dont deux par groupe en mixte.');const used=new Set(teams.flat());return {number,matches,byes:active.filter(p=>!used.has(p.id)).map(p=>p.id)};}
export function createGame(config){if(!formats[config.format]||!rules[config.rule])throw Error('Format inconnu.');const names=s=>s.split('\n').map(n=>n.trim()).filter(Boolean);const a=names(config.names),b=mixed(config.format)?names(config.namesB):[];const all=[...a,...b];if(all.length<4||all.length>64)throw Error('Indiquez entre 4 et 64 joueurs.');if(new Set(all.map(n=>n.toLowerCase())).size!==all.length)throw Error('Donnez un nom distinct à chaque joueur.');if(all.some(n=>n.length>60))throw Error('Un nom ne doit pas dépasser 60 caractères.');if(fixed(config.format)&&all.length%2)throw Error('Les équipes fixes demandent un nombre pair de joueurs.');if(mixed(config.format)&&(a.length<2||b.length<2))throw Error('Il faut au moins deux joueurs dans chaque groupe.');for(const [key,min,max] of [['courts',1,16],['minutes',1,120],['target',2,999],['roundCount',1,100]])if(!Number.isInteger(config[key])||config[key]<min||config[key]>max)throw Error('Vérifiez les nombres saisis.');const g={...config,id:crypto.randomUUID(),created:Date.now(),seed:Math.floor(Math.random()*1e8),players:all.map((name,i)=>({id:`p${i}`,name,group:i<a.length?'A':'B'})),rounds:[],withdrawn:[],revisions:[],timer:null,closed:false};if(config.format==='TEAM_AMERICANO')g.roundCount=all.length/2-1+(all.length/2%2);const n=dynamic(g.format)?1:g.roundCount;for(let i=0;i<n;i++)g.rounds.push(makeRound(g));return g;}
export function wave(g){for(const r of g.rounds)for(let i=0;i<r.matches.length;i+=g.courts){const ms=r.matches.slice(i,i+g.courts);if(ms.some(m=>m.status!=='done'))return {round:r.number,key:`${r.number}:${i}`,matches:ms};}return null;}
export function advance(g){if(!wave(g)&&!g.closed&&g.rounds.length<g.roundCount)g.rounds.push(makeRound(g));}
export function expire(g,now=Date.now()){if(!g.timer?.deadline||g.timer.deadline>now)return false;const w=wave(g);if(g.rule==='TIMED'&&w?.key===g.timer.key)for(const m of w.matches)m.status='done';g.timer=null;advance(g);return true;}
function validateContent(data){if(data?.version!==1||!Array.isArray(data.games)||data.games.length>200)throw Error('Sauvegarde incompatible.');for(const g of data.games){if(!formats[g.format]||!rules[g.rule]||!Array.isArray(g.players)||g.players.length<4||g.players.length>64||!Array.isArray(g.rounds)||g.rounds.length>100)throw Error('Partie invalide.');for(const [k,min,max] of [['courts',1,16],['minutes',1,120],['target',2,999],['roundCount',1,100]])if(!Number.isInteger(g[k])||g[k]<min||g[k]>max)throw Error('Configuration invalide.');if(typeof g.id!=='string'||typeof g.title!=='string'||!Number.isFinite(g.seed)||!Array.isArray(g.withdrawn)||!Array.isArray(g.revisions))throw Error('Partie invalide.');const ids=new Set(g.players.map(p=>p.id));if(ids.size!==g.players.length||g.players.some(p=>typeof p.id!=='string'||typeof p.name!=='string'||p.name.length>60||!['A','B'].includes(p.group)))throw Error('Joueurs invalides.');const keys=new Set();for(const r of g.rounds){if(!Array.isArray(r.matches)||!r.matches.length||r.matches.length>16||!Array.isArray(r.byes))throw Error('Manche invalide.');const used=new Set();for(const m of r.matches){if(keys.has(m.id)||!Array.isArray(m.teams)||m.teams.length!==2||m.teams.some(t=>!Array.isArray(t)||t.length!==2)||!Array.isArray(m.score)||m.score.length!==2||!m.score.every(n=>Number.isInteger(n)&&n>=0&&n<=9999)||!['scheduled','running','done'].includes(m.status))throw Error('Match invalide.');keys.add(m.id);for(const id of m.teams.flat()){if(!ids.has(id)||used.has(id))throw Error('Joueur dupliqué dans une manche.');used.add(id);}if(m.status==='done'&&!validFinal(...m.score,g.rule,g.target))throw Error('Score final invalide.');}if(r.byes.some(id=>!ids.has(id)||used.has(id)))throw Error('Repos invalide.');}if(g.timer&&(!Number.isFinite(g.timer.remaining)||g.timer.remaining<0||g.timer.remaining>7200000||typeof g.timer.key!=='string'||g.timer.deadline!==null&&!Number.isFinite(g.timer.deadline)))throw Error('Chronomètre invalide.');}return data;}
